before_install:
  - sudo apt-get -qq update
install: make get-deps
language: c

jobs:
  include:
  - stage: nagios3
    script: make nagios3
    before_deploy:
    - mv src/alerta-neb.o src/alerta-neb.o.nagios3
    deploy:
    - provider: releases
      skip-cleanup: true
      api_key: "$GITHUB_TOKEN"
      file: src/alerta-neb.o.nagios3
      on:
        tags: true
        branch: master
  - stage: nagios4
    script: make nagios4
    before_deploy:
    - mv src/alerta-neb.o src/alerta-neb.o.nagios4
    deploy:
    - provider: releases
      skip-cleanup: true
      api_key: "$GITHUB_TOKEN"
      file: src/alerta-neb.o.nagios4
      on:
        tags: true
        branch: master
  - stage: naemon
    script: make naemon
    before_deploy:
    - mv src/alerta-neb.o src/alerta-neb.o.naemon
    deploy:
    - provider: releases
      skip-cleanup: true
      api_key: "$GITHUB_TOKEN"
      file: src/alerta-neb.o.naemon
      on:
        tags: true
        branch: master
